//Library for Php Objects
//Deep Html  [V.0.0.2]  (2017-02-20)
//Spc - Cica_d05 - Home - Index_06 - v0_0_1
//- Base Parts Flat
//Common structures
//Container
//Flex Slider
//Header
//Footer
//Email
//Svg Circle
//Phone
//Descriptions
var supermnu_thm = supermnu_libs + "theme/" + theme_name + "/";
var supermnu_com = supermnu_libs + "theme/common/";

require(supermnu_com + "/structures/spans/spa01_span_span.struc");

require(supermnu_com + "/structures/divs/div01_div_div.struc");

require(supermnu_thm + "main_html/ctn01_container_" + theme_name + ".obj");

require(supermnu_thm + "deep_html/types/slider/flx03_div_flex_carousel.middle");

require(supermnu_thm + "deep_html/types/slider/flx03_div_flex_slider.middle");

require(supermnu_thmcica + "deep_html/regions/middle/slide/flex/flx01_li_flex.middle");

require(supermnu_thmcica + "deep_html/regions/middle/slide/flex/flx02_ul_flex.middle");

require(supermnu_thm + "deep_html/types/header/hdr02_div.header");

require(supermnu_thm + "deep_html/types/header/hdr01_svg.header");

require(supermnu_thm + "deep_html/types/footer/foo01_svg.footer");

require(supermnu_thm + "deep_html/types/footer/foo02_em.footer");

require(supermnu_thm + "deep_html/types/footer/foo03_div.footer");

require(supermnu_thm + "deep_html/types/footer/foo04_footer.footer");

require(supermnu_thm + "deep_html/types/email/mai01_svg.middle");

require(supermnu_thm + "deep_html/types/email/mai02_div_mail_icon.middle");

require(supermnu_thm + "deep_html/types/email/mai02_div_mail_address.middle");

require(supermnu_thm + "deep_html/types/email/mai03_div_mail.middle");

require(supermnu_thm + "deep_html/types/circle/cir02_div_circle_rect.middle");

require(supermnu_thm + "deep_html/types/circle/rec01_rect.middle");

require(supermnu_thm + "deep_html/types/circle/cir01_circle.middle");

require(supermnu_thm + "deep_html/types/phone/phn02_div_phone_icon.middle");

require(supermnu_thm + "deep_html/types/phone/phn02_div_phone_address.middle");

require(supermnu_thm + "deep_html/types/phone/phn03_div_phone.middle");

require(supermnu_thm + "deep_html/types/descriptions/des02_div_descriptions.middle");

require(supermnu_thm + "deep_html/types/descriptions/des01_p_parragraph.middle");

require(supermnu_thm + "deep_html/types/mobile_contacts/mob02_div_email.middle");

require(supermnu_thm + "deep_html/types/mobile_contacts/mob02_div_phone.middle");

require(supermnu_thm + "deep_html/types/mobile_contacts/mob03_div_mobile.middle");
