//Library for Php Objects
//DMode  [V.0.0.2]  (2017-02-20)
//Spc - Cica_d05 - Home - Index_06 - v0_0_1

if (!(undefined !== supermnu_drupal)) //print ('Enter Isset A'. '</br>' )											;
	{
		var supermnu_drupal = "/home/ser/zd/main/es/zdom/emp/flat/zd_main_flat/es/rphp/objects/drupal";
	}

require(supermnu_drupal + "dmode/common.dmode");

require(supermnu_drupal + "dmode/d13_blockbase.dmode");

require(supermnu_drupal + "dmode/d12_tagadelic.dmode");

require(supermnu_drupal + "dmode/d11_view_simple.dmode");

require(supermnu_drupal + "dmode/d10_simple_image.dmode");

require(supermnu_drupal + "dmode/d09_view_image.dmode");

require(supermnu_drupal + "dmode/d08_image.dmode");
