//Library for Php Objects
//Fast Node  [V.0.0.2]  (2017-02-20)
//Spc - Cica_d05 - Home - Index_06 - v0_0_1
//- Fast Nodes - FNode - FMode
//- Fast Nodes - INode
var supermnu_thm = supermnu_libs + "theme/" + theme_name + "/";
var supermnu_fnode = supermnu_thm + "fast_node/fnode/";
var supermnu_inode = supermnu_thmcica + "fast_node/inode/";

require(supermnu_fnode + "fn01_flat.fnode");

require(supermnu_fnode + "fn02_images.fnode");

require(supermnu_fnode + "fn03_links.fnode");

require(supermnu_fnode + "fn04_phone.fnode");

require(supermnu_inode + "in01_path.inode");
