//Library for Php Objects
//Deep Html  [V.0.0.2]  (2017-02-20)
//Spc - Cica_d05 - Home - Index_06 - v0_0_1
//- Base Parts Flat
//Common structures
//Flex Slider
//Header
///ssd/home/ser/zd/main/es/zdom/emp/truck/zd_main_truck/es/rphp/theme/truck/deep_html/types/header/hdr02_div.header
//print ($supermnu_thm. 'deep_html/types/header/hdr02_div.header' . $br)								;
//Footer
//Email
//Marquee
//Flags
//Captcha
//Desc List
//Phone
//Descriptions
//Truck Links
//Cookies
var supermnu_thm = supermnu_libs + "theme/" + theme_name + "/";
var supermnu_com = supermnu_libs + "theme/common/";

require(supermnu_com + "/structures/spans/spa01_span_span.struc");

require(supermnu_com + "/structures/divs/div01_div_div.struc");

require(supermnu_com + "/structures/sections/sec01_section_p.struc");

require(supermnu_com + "/structures/sections/sec02_section_h2.struc");

require(supermnu_com + "/structures/p/lnk01_p_strong.struc");

require(supermnu_thm + "deep_html/types/slider/flx03_div_flex_carousel.middle");

require(supermnu_thm + "deep_html/types/slider/flx03_div_flex_slider.middle");

require(supermnu_com + "deep_html/slider/flx01_li_flex.middle");

require(supermnu_com + "deep_html/slider/flx02_ul_flex.middle");

require(supermnu_com + "deep_html/slider/flx02_ul_product_flex.middle");

require(supermnu_thm + "deep_html/types/header/hdr02_div.header");

require(supermnu_thm + "deep_html/types/footer/foo02_a.footer");

require(supermnu_thm + "deep_html/types/footer/foo03_div.footer");

require(supermnu_thm + "deep_html/types/footer/foo04_footer.footer");

require(supermnu_thm + "deep_html/types/email/mai02_div_mail_icon.middle");

require(supermnu_thm + "deep_html/types/email/mai02_div_mail_address.middle");

require(supermnu_thm + "deep_html/types/email/mai03_div_mail.middle");

require(supermnu_thm + "deep_html/types/marquee/mar01_div_marquee.middle");

require(supermnu_thm + "deep_html/types/flags/flg01_div_flags.middle");

require(supermnu_thm + "deep_html/types/flags/flg02_div_flags.middle");

require(supermnu_thm + "deep_html/types/flags/flg03_div_flags.middle");

require(supermnu_thm + "deep_html/types/captcha/cpt01_button_captcha.middle");

require(supermnu_thm + "deep_html/types/captcha/cpt02_div_captcha.middle");

require(supermnu_thm + "deep_html/types/captcha/cpt03_div_captcha.middle");

require(supermnu_thm + "deep_html/types/captcha/cpt04_div_captcha.middle");

require(supermnu_thm + "deep_html/types/desc_list/dli01_desc_list.middle");

require(supermnu_thm + "deep_html/types/phone/phn02_div_phone_icon.middle");

require(supermnu_thm + "deep_html/types/phone/phn02_div_phone_address.middle");

require(supermnu_thm + "deep_html/types/phone/phn03_div_phone.middle");

require(supermnu_thm + "deep_html/types/descriptions/des02_div_descriptions.middle");

require(supermnu_thm + "deep_html/types/descriptions/des01_p_parragraph.middle");

require(supermnu_thm + "deep_html/types/mobile_contacts/mob02_div_email.middle");

require(supermnu_thm + "deep_html/types/mobile_contacts/mob02_div_phone.middle");

require(supermnu_thm + "deep_html/types/mobile_contacts/mob03_div_mobile.middle");

require(supermnu_thm + "deep_html/types/links/lks02_div_truck.middle");

require(supermnu_thm + "deep_html/types/cookies/cok01_div_cookies.middle");
