//Library for Php Objects - Truck
//Fast Node  [V.0.0.2]  (2017-07-06)
//Spc - Cica_d05 - Home - Index_06 - v0_0_1
//- Fast Nodes - FNode - FMode
//- Fast Nodes - Common
//- Fast Node Flat
//- Fast Nodes - INode
var supermnu_thm = supermnu_libs + "theme/" + theme_name + "/";
var supermnu_fnode = supermnu_thm + "fast_node/fnode/";
var supermnu_inode = supermnu_thmcica + "fast_node/inode/";
var supermnu_pnodecom = supermnu_com + "fast_node/pnode/";
var supermnu_fnodecom = supermnu_com + "fast_node/fnode/";

require(supermnu_fnodecom + "fy01_cookies.fnode");

require(supermnu_fnodecom + "fn01_lang_common.fnode");

require(supermnu_fnodecom + "fn01_flat.fnode");

require(supermnu_fnodecom + "fn02_images.fnode");

require(supermnu_fnodecom + "fn03_site_common.fnode");

require(supermnu_fnode + "fn11_links_common.fnode");

require(supermnu_fnode + "fn12_links_lang.fnode");

require(supermnu_fnode + "fn21_phone_common.fnode");

require(supermnu_fnode + "fn22_phone_lang.fnode");

require(supermnu_fnode + "fn23_site_lang.fnode");

require(supermnu_fnode + "fn31_cookies.fnode");

require(supermnu_fnode + "fn32_cookies_links.fnode");

require(supermnu_inode + "in01_path.inode");

require(supermnu_inode + "sv01_svg.inode");
