//Library for Php Objects - Truck
//Main Html  [V.0.0.2]  (2017-02-20)
//Spc - Cica_d05 - Home - Index_06 - v0_0_1
//- Level 1 - Header
//print ("Before_Head" . $br)													;
//Container
//- Level 0 - Row and section
//- Level 0 - Scripts
var supermnu_thm = supermnu_libs + "theme/" + theme_name + "/";

require(supermnu_thm + "main_html/hea01_head_" + theme_name + ".obj");

require(supermnu_thm + "main_html/hdr01_header_" + theme_name + ".obj");

require(supermnu_thm + "main_html/ctn01_container_" + theme_name + ".obj");

require(supermnu_thm + "main_html/sid01_sidebars_" + theme_name + ".obj");

require(supermnu_thm + "main_html/bdy01_body_" + theme_name + ".obj");

require(supermnu_thm + "main_html/met01_meta_" + theme_name + ".obj");

require(supermnu_thm + "main_html/lnk01_link_" + theme_name + ".obj");

require(supermnu_thm + "main_html/htm01_html_" + theme_name + ".obj");

require(supermnu_thm + "main_html/htm02_fast_" + theme_name + ".obj");

require(supermnu_thm + "main_html/row01_div_" + theme_name + ".obj");

require(supermnu_thm + "main_html/sec01_section_lang_" + theme_name + ".obj");

require(supermnu_thm + "main_html/sec02_section_slider_" + theme_name + ".obj");

require(supermnu_thm + "main_html/scr01_js_" + theme_name + ".script");
