//Library for Uri Objects
//Deep Html  [V.0.0.2]  (2017-02-20)
//Spc - Cica_d05 - Home - Index_06 - v0_0_1
//Var needed: supermnu_drupal
//Uri Definitions
var supermnu_drupal = supermnu_libs + "objects/drupal/";
var supermnu_disk = supermnu_libs + "objects/disk/";
var supermnu_uri = supermnu_drupal + "uri/";

require(supermnu_uri + "u08_defs_common.uri");

require(supermnu_uri + "u07_defs_paths.uri");

require(supermnu_uri + "u06_defs_urls.uri");

require(supermnu_uri + "u05_sets.uri");

require(supermnu_uri + "u04_urls.uri");

require(supermnu_uri + "u03_paths.uri");

require(supermnu_uri + "u02_front.uri");

require(supermnu_uri + "u01_uri.obj");
